apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: vikkzldemoacr.azurecr.io/azvote/azure-vote-front
    newTag: beee6a0ddc742a32ab841c4585760ac117178e61
  - name: vikkzldemoacr.azurecr.io/azvote/azure-vote-back
    newTag: beee6a0ddc742a32ab841c4585760ac117178e61
resources:
  - manifests.yaml