apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fluxdemoacr.azurecr.io/azvote/azure-vote-front
    newTag: 374acd3eb362f89f8868687f0a8fd551e85abf27
  - name: fluxdemoacr.azurecr.io/azvote/azure-vote-back
    newTag: 374acd3eb362f89f8868687f0a8fd551e85abf27
resources:
  - manifests.yaml