apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fluxdemoacr.azurecr.io//azure-vote-front
    newTag: 203828d2c82981b50067a5d147726fee4cfeb3a4
  - name: fluxdemoacr.azurecr.io//azure-vote-back
    newTag: 203828d2c82981b50067a5d147726fee4cfeb3a4
resources:
  - manifests.yaml