apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: vikkzldemoacr.azurecr.io/azvote/azure-vote-front
    newTag: 348c5d20b5831e8d7d16c55e5dbddafe99a5d7d4
  - name: vikkzldemoacr.azurecr.io/azvote/azure-vote-back
    newTag: 348c5d20b5831e8d7d16c55e5dbddafe99a5d7d4
resources:
  - manifests.yaml