apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage

images:
  - name: vikkzldemoacr.azurecr.io/azvote/azure-vote-front
    newTag: f7a77d1e98a498e70582308bc8841d9a544f0c44
  - name: vikkzldemoacr.azurecr.io/azvote/azure-vote-back
    newTag: f7a77d1e98a498e70582308bc8841d9a544f0c44
resources:
  - manifests.yaml